name: Zones
version: '${version}'
main: de.t14d3.zones.bukkit.ZonesBukkit
author: T14D3
website: https://github.com/t14d3/zones
description: Modern region protection plugin/mod
api-version: '1.21'
softdepend: [ WorldEdit, FastAsyncWorldEdit, PlaceholderAPI, WorldGuard ]
libraries:
  - "com.h2database:h2:2.3.232"
  - "org.postgresql:postgresql:42.7.2"